Summary: GNU tool for automatically configuring source code
Name: autoconf
Version: 2.62
Revision: 1
Copyright: GPL2
Source: ftp://ftp.gnu.org/gnu/autoconf/autoconf-2.62.tar.gz
BuildRoot: /var/tmp/%{name}-%{version}-%{revision}-buildroot

%description

Autoconf is an extensible package of m4 macros that produce shell scripts to automatically configure software source code packages. These scripts can adapt the package to many kinds of UNIX-like systems without manual user intervention.
 
%prep
%setup -q

%build
./configure --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/libexec --datadir=/usr/share --sysconfdir=/usr/etc --sharedstatedir=/usr/com --localstatedir=/usr/var --libdir=/usr/lib --includedir=/usr/include --oldincludedir=/usr/include --infodir=/usr/info --mandir=/usr/man --without-lispdir 
make

%makeinstall

%changelog
- generated by apkg 0.7 - heuristic [automake] 1.0
