#!/bin/sh
# file: autoconf-2.62-1.sh

# pkg-name: autoconf
# pkg-version: 2.62
# pkg-revision: 1
# copyright: GPL2
# summary: GNU tool for automatically configuring source code

./configure --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/libexec --datadir=/usr/share --sysconfdir=/usr/etc --sharedstatedir=/usr/com --localstatedir=/usr/var --libdir=/usr/lib --includedir=/usr/include --oldincludedir=/usr/include --infodir=/usr/info --mandir=/usr/man --without-lispdir 
make
make DESTDIR=$TMP install 

# generated by apkg 0.7 - heuristic [automake] 1.0
