# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcMAINFRAME(wx.Frame): 
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "MAINFRAME")
        self.PostCreate(pre)

        # create attributes for the named items in this container
        self.rwqer = xrc.XRCCTRL(self, "rwqer")
        self.InformationPanel = xrc.XRCCTRL(self, "InformationPanel")
        self.InfoText1 = xrc.XRCCTRL(self, "InfoText1")
        self.BuildPanel = xrc.XRCCTRL(self, "BuildPanel")
        self.fsa = self.GetMenuBar()
        idx = self.GetMenuBar().FindMenu("File")
        if idx != wx.NOT_FOUND:
            self.FileMenu = self.GetMenuBar().GetMenu(idx)
        else:
            self.FileMenu = self.GetMenuBar().FindItemById(xrc.XRCID("FileMenu")).GetSubMenu()
        self.FileNew = self.GetMenuBar().FindItemById(xrc.XRCID("FileNew"))
        self.FileOpen = self.GetMenuBar().FindItemById(xrc.XRCID("FileOpen"))
        self.FileSave = self.GetMenuBar().FindItemById(xrc.XRCID("FileSave"))
        self.FileQuit = self.GetMenuBar().FindItemById(xrc.XRCID("FileQuit"))
        idx = self.GetMenuBar().FindMenu("Documentation")
        if idx != wx.NOT_FOUND:
            self.DocumentationMenu = self.GetMenuBar().GetMenu(idx)
        else:
            self.DocumentationMenu = self.GetMenuBar().FindItemById(xrc.XRCID("DocumentationMenu")).GetSubMenu()
        idx = self.GetMenuBar().FindMenu("Help")
        if idx != wx.NOT_FOUND:
            self.HelpMenu = self.GetMenuBar().GetMenu(idx)
        else:
            self.HelpMenu = self.GetMenuBar().FindItemById(xrc.XRCID("HelpMenu")).GetSubMenu()
        self.HelpAbout = self.GetMenuBar().FindItemById(xrc.XRCID("HelpAbout"))



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    xmlEditor_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="MAINFRAME">
    <title>apkg - XML builder (1.0)</title>
    <centered>1</centered>
    <pos>1,1</pos>
    <size>640,800</size>
    <style>wxDEFAULT_FRAME_STYLE|wxCAPTION|wxSTAY_ON_TOP|wxMAXIMIZE_BOX|wxTAB_TRAVERSAL</style>
    <enabled>1</enabled>
    <tooltip>This tool can help you create/modify a build control XML file.</tooltip>
    <object class="wxNotebook" name="rwqer">
      <pos>200,300</pos>
      <size>400,300</size>
      <object class="notebookpage">
        <label>Information</label>
        <object class="wxPanel" name="InformationPanel">
          <object class="wxStaticText" name="InfoText1">
            <label>namesdf</label>
            <pos>50,50</pos>
            <size>150,150</size>
            <enabled>1</enabled>
            <focused>1</focused>
          </object>
        </object>
        <selected>1</selected>
      </object>
      <object class="notebookpage">
        <label>Build</label>
        <object class="wxPanel" name="BuildPanel"/>
        <selected>0</selected>
      </object>
    </object>
    <object class="wxMenuBar" name="fsa">
      <style/>
      <fg>#FFFFFF</fg>
      <bg>#FFFFFF</bg>
      <object class="wxMenu" name="FileMenu">
        <label>File</label>
        <object class="wxMenuItem" name="FileNew">
          <label>New</label>
        </object>
        <object class="wxMenuItem" name="FileOpen">
          <label>Open</label>
        </object>
        <object class="wxMenuItem" name="FileSave">
          <label>Save</label>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem" name="FileQuit">
          <label>Quit</label>
        </object>
      </object>
      <object class="wxMenu" name="DocumentationMenu">
        <label>Documentation</label>
        <help/>
      </object>
      <object class="wxMenu" name="HelpMenu">
        <label>Help</label>
        <object class="wxMenuItem" name="HelpAbout">
          <label>About</label>
        </object>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/xmlEditor/xmlEditor_xrc', xmlEditor_xrc)
    __res.Load('memory:XRC/xmlEditor/xmlEditor_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("apkg - XML builder (1.0)")
    _("This tool can help you create/modify a build control XML file.")
    _("Information")
    _("namesdf")
    _("Build")
    _("File")
    _("New")
    _("Open")
    _("Save")
    _("Quit")
    _("Documentation")
    _("Help")
    _("About")

